name: Build & Deploy Jekyll site

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    container:
      image: docker://docker.pkg.github.com/${{ github.repository }}/mickey:latest
      
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t mickey:latest .

    - name: Run Gulp → build site
      run: |
        docker run --rm -v ${{ github.workspace }}:/srv/jekyll mickey:latest

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        # if using a custom domain:
        # cname: example.com
