name: Build & Deploy Jekyll site

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Build your Dockerfile here instead of pulling
    container:
      build:
        context: .
        dockerfile: Dockerfile

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Gulp → build site
        run: |
          # the container is already your Jekyll+Gulp environment
          gulp build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
