name: Build & Deploy Jekyll site

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (for multi-platform caching, optional)
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
            --tag mickey:latest \
            .

      - name: Run Python build
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/srv/jekyll" \
            mickey:latest

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
